import { NextResponse } from "next/server";

import { supabaseServer } from "@/lib/supabase/server";
import {
  findLikelyPii,
  isEventType,
  isPrimitivePayload,
  isUuid,
  MAX_PAYLOAD_BYTES,
  PAYLOAD_KEYS,
  type PayloadValue,
  deviceType,
  geography,
  referrerType,
} from "@/lib/analytics/schema";
import { isLocale } from "@/lib/content/types";

/**
 * Analytics ingest. POST only.
 *
 * What this endpoint stores:
 *   sessions — an anonymous UUID the client generated, plus locale, a referrer
 *              CATEGORY, a device bucket, and approximate geography (country
 *              and city, resolved at the edge — the IP is never read)
 *   events   — the session id, an allowlisted type, and an allowlisted payload
 *
 * What it deliberately does NOT store, and never will:
 *   - the IP address. It is present on the request; we never read it
 *   - the User-Agent. Read once to bucket the device, then discarded
 *   - the referrer URL. Only its category, because a referrer can itself carry
 *     personal information
 *   - anything that looks like an email, phone number, or long digit string,
 *     even under an allowlisted key
 *
 * These are published claims (Layer 2, /how-this-site-works), so they are
 * enforced here rather than left to callers behaving well.
 */

export const dynamic = "force-dynamic";

type Body = {
  sessionId?: unknown;
  type?: unknown;
  payload?: unknown;
  locale?: unknown;
};

function bad(message: string, status = 400) {
  return NextResponse.json({ error: message }, { status });
}

export async function POST(request: Request) {
  let body: Body;
  try {
    body = (await request.json()) as Body;
  } catch {
    return bad("Invalid JSON body");
  }

  if (!isUuid(body.sessionId)) {
    return bad("`sessionId` must be a UUID generated by the client");
  }
  if (!isEventType(body.type)) {
    return bad("`type` is not a known event type");
  }

  // --- payload validation -------------------------------------------------
  let payload: Record<string, PayloadValue> | null = null;

  if (body.payload !== undefined && body.payload !== null) {
    if (
      typeof body.payload !== "object" ||
      Array.isArray(body.payload)
    ) {
      return bad("`payload` must be an object");
    }

    const candidate = body.payload as Record<string, unknown>;

    if (JSON.stringify(candidate).length > MAX_PAYLOAD_BYTES) {
      return bad(`\`payload\` exceeds ${MAX_PAYLOAD_BYTES} bytes`);
    }

    // Allowlist, not blocklist: an unknown key cannot arrive by accident and
    // quietly start collecting something.
    const allowed = PAYLOAD_KEYS[body.type];
    const unknownKeys = Object.keys(candidate).filter((k) => !allowed.includes(k));
    if (unknownKeys.length > 0) {
      return bad(
        `\`payload\` has keys not allowed for ${body.type}: ${unknownKeys.join(", ")}`,
      );
    }

    // Nested structures are how personal data arrives under an allowlisted
    // top-level key, e.g. { source: { email: "…" } }.
    if (!isPrimitivePayload(candidate)) {
      return bad("`payload` values must be strings, numbers, booleans or null");
    }

    // Backstop against an allowed key carrying a value it should never hold.
    const pii = findLikelyPii(candidate);
    if (pii) {
      return bad(`Rejected: ${pii}. Events never carry personal data.`, 422);
    }

    payload = candidate;
  }

  const locale =
    typeof body.locale === "string" && isLocale(body.locale) ? body.locale : null;

  /*
   * The session row is created on first sight of its id. The client owns the
   * id; the server never mints one and never links it to anything.
   *
   * `ignoreDuplicates` means a returning event for a known session is a no-op
   * rather than an overwrite — so the first-seen locale/referrer/device stand,
   * and one session cannot be rewritten by a later request.
   */
  // Country and city come from headers Vercel resolved at the edge. The raw
  // address is never present in this handler.
  const { country, city } = geography(request.headers);

  const { error: sessionError } = await supabaseServer
    .from("sessions")
    .upsert(
      {
        id: body.sessionId,
        locale,
        // Category only — the URL itself is never stored.
        referrer_type: referrerType(request.headers.get("referer")),
        // UA read here and discarded; only the bucket is persisted.
        device: deviceType(request.headers.get("user-agent")),
        country,
        city,
      },
      { onConflict: "id", ignoreDuplicates: true },
    );

  if (sessionError) {
    return bad(`Failed to record session: ${sessionError.message}`, 500);
  }

  const { error: eventError } = await supabaseServer.from("events").insert({
    session_id: body.sessionId,
    type: body.type,
    payload,
  });

  if (eventError) {
    return bad(`Failed to record event: ${eventError.message}`, 500);
  }

  // 204: nothing to return, and nothing the client should act on.
  return new NextResponse(null, { status: 204 });
}
